print("=" * 50)
print("STARTING MY CYBERSECURITY JOURNEY!")
print("=" * 50)
print()
print("Start Date: December 28, 2025")
print("Goal: Master cybersecurity in 3 months")
print("Certifications Target: Network+ & Security+")
print("Focus: Python + Security Tools")
print()
print("Let's get it!")
print("=" * 50)